export const HERITAGE_PREP_FEE_CLIENT_NAME = 'Heritage Kids Press';

export type HeritagePrepFeeOverrideRow = {
  shipDate: string;
  orderNumber: string;
  recipientName: string;
  itemNames: string;
  qty: number;
  shippingTotal: number;
  boxName: string;
  pickpackTotal: number;
  packageTotal: number;
  storageTotal: number;
  rowTotal: number;
};

export const HERITAGE_PREP_FEE_OVERRIDES: HeritagePrepFeeOverrideRow[] = [
  {
    "shipDate": "2026-04-01",
    "orderNumber": "SP6065",
    "recipientName": "Lernni Mahal Juco-Hoang",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.96,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 10.16
  },
  {
    "shipDate": "2026-04-01",
    "orderNumber": "SP6066",
    "recipientName": "Mary Grace Yniguez",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.92,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.42
  },
  {
    "shipDate": "2026-04-01",
    "orderNumber": "SP6067",
    "recipientName": "Sammy Woodring",
    "itemNames": "KOREAN - FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-01",
    "orderNumber": "SP6068",
    "recipientName": "Lam Do",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-01",
    "orderNumber": "SP6069",
    "recipientName": "Sylvia Shaw",
    "itemNames": "SPANISH SONG BOOK - CHILDREN SONGS",
    "qty": 1.0,
    "shippingTotal": 5.22,
    "boxName": "12x10x3",
    "pickpackTotal": 2.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 8.27
  },
  {
    "shipDate": "2026-04-01",
    "orderNumber": "SP6070",
    "recipientName": "Nuela Parawan",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-01",
    "orderNumber": "SP6071",
    "recipientName": "Summer Tentoni",
    "itemNames": "CHINESE - MY FIRST WORD SERIES [SIMPLIFIED] | KOREAN - FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 7.47,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 10.67
  },
  {
    "shipDate": "2026-04-01",
    "orderNumber": "SP6072",
    "recipientName": "Monica Rutherford",
    "itemNames": "KOREAN - FIRST WORD SERIES | KOREAN SONG BOOK - NURSERY RHYMES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-01",
    "orderNumber": "SP6073",
    "recipientName": "Bianca Nguyen",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.38,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 9.58
  },
  {
    "shipDate": "2026-04-02",
    "orderNumber": "SP6074",
    "recipientName": "In ok Kim",
    "itemNames": "KOREAN SONG BOOK - NURSERY RHYMES",
    "qty": 1.0,
    "shippingTotal": 5.22,
    "boxName": "12x10x3",
    "pickpackTotal": 2.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 8.27
  },
  {
    "shipDate": "2026-04-02",
    "orderNumber": "SP6076",
    "recipientName": "Krystle Parinas",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-02",
    "orderNumber": "SP6077",
    "recipientName": "Robert Nguyen",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-02",
    "orderNumber": "SP6078",
    "recipientName": "Conchita Rubio",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-02",
    "orderNumber": "SP6079",
    "recipientName": "Jenny Calabrese",
    "itemNames": "KOREAN SONG BOOK - ANIMAL SONGS | KOREAN SONG BOOK - CHILDREN SONGS | KOREAN SONG BOOK - NURSERY RHYMES",
    "qty": 3.0,
    "shippingTotal": 7.19,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 11.24
  },
  {
    "shipDate": "2026-04-02",
    "orderNumber": "SP6080",
    "recipientName": "Nicolette Rolda",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-02",
    "orderNumber": "SP6081",
    "recipientName": "Ariane Valeroso",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-02",
    "orderNumber": "SP6082",
    "recipientName": "Mary Megel",
    "itemNames": "KOREAN SONG BOOK - ANIMAL SONGS | KOREAN SONG BOOK - CHILDREN SONGS | KOREAN SONG BOOK - NURSERY RHYMES | KOREAN - FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 8.97,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 13.71
  },
  {
    "shipDate": "2026-04-03",
    "orderNumber": "SP6083",
    "recipientName": "Rholan Pierre",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-03",
    "orderNumber": "SP6084",
    "recipientName": "Tec Sun",
    "itemNames": "KOREAN SONG BOOK - ANIMAL SONGS | KOREAN SONG BOOK - CHILDREN SONGS | KOREAN SONG BOOK - NURSERY RHYMES | KOREAN - FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 8.97,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 13.71
  },
  {
    "shipDate": "2026-04-03",
    "orderNumber": "SP6086",
    "recipientName": "Janice Lee",
    "itemNames": "KOREAN - FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-03",
    "orderNumber": "SP6087",
    "recipientName": "grace lubag",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-03",
    "orderNumber": "SP6088",
    "recipientName": "Camila de Paula",
    "itemNames": "PORTUGUESE - MY FIRST WORD SERIES | PORTUGUESE - BRAZILIANS NURSERY RHYMES",
    "qty": 2.0,
    "shippingTotal": 6.77,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.32
  },
  {
    "shipDate": "2026-04-03",
    "orderNumber": "SP6091",
    "recipientName": "JOS VILLALUNA",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - CHILDREN SONGS | TAGALOG - MY FIRST WORD SERIES",
    "qty": 3.0,
    "shippingTotal": 7.68,
    "boxName": "11x9x6",
    "pickpackTotal": 3.5,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 11.92
  },
  {
    "shipDate": "2026-04-03",
    "orderNumber": "SP6092",
    "recipientName": "Clara Louise Fernandez",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.25,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 9.25
  },
  {
    "shipDate": "2026-04-03",
    "orderNumber": "SP6093",
    "recipientName": "Kevin Lee",
    "itemNames": "CHINESE - MY FIRST WORD SERIES [TRADITIONAL]",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-03",
    "orderNumber": "SP6095",
    "recipientName": "Francesca Yi",
    "itemNames": "KOREAN SONG BOOK - ANIMAL SONGS | KOREAN SONG BOOK - CHILDREN SONGS | KOREAN SONG BOOK - NURSERY RHYMES",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-03",
    "orderNumber": "SP6096",
    "recipientName": "Minna Choi",
    "itemNames": "CHINESE - MY FIRST WORD SERIES [SIMPLIFIED] | KOREAN SONG BOOK - NURSERY RHYMES | KOREAN - FIRST WORD SERIES",
    "qty": 3.0,
    "shippingTotal": 8.22,
    "boxName": "11x9x6",
    "pickpackTotal": 3.5,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 12.46
  },
  {
    "shipDate": "2026-04-03",
    "orderNumber": "SP6097",
    "recipientName": "Peter Orlando",
    "itemNames": "PORTUGUESE - MY FIRST WORD SERIES | PORTUGUESE - BRAZILIANS NURSERY RHYMES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-04",
    "orderNumber": "SP6098",
    "recipientName": "Grace Kim",
    "itemNames": "KOREAN SONG BOOK - ANIMAL SONGS | KOREAN SONG BOOK - CHILDREN SONGS | KOREAN SONG BOOK - NURSERY RHYMES | KOREAN - FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 8.97,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 13.71
  },
  {
    "shipDate": "2026-04-04",
    "orderNumber": "SP6099",
    "recipientName": "Christine Schafer Cosca",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-04",
    "orderNumber": "SP6100",
    "recipientName": "Ashley Park",
    "itemNames": "KOREAN SONG BOOK - ANIMAL SONGS | KOREAN SONG BOOK - CHILDREN SONGS | KOREAN SONG BOOK - NURSERY RHYMES | KOREAN - FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 6.96,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 11.7
  },
  {
    "shipDate": "2026-04-04",
    "orderNumber": "SP6101",
    "recipientName": "Mia Vargas",
    "itemNames": "PORTUGUESE - BRAZILIANS NURSERY RHYMES",
    "qty": 1.0,
    "shippingTotal": 5.22,
    "boxName": "12x10x3",
    "pickpackTotal": 2.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 8.27
  },
  {
    "shipDate": "2026-04-04",
    "orderNumber": "SP6102",
    "recipientName": "Mia \"Percy\" Peterson",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES",
    "qty": 1.0,
    "shippingTotal": 5.22,
    "boxName": "12x10x3",
    "pickpackTotal": 2.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 8.27
  },
  {
    "shipDate": "2026-04-04",
    "orderNumber": "SP6103",
    "recipientName": "Charlotte Greenhaw",
    "itemNames": "PORTUGUESE - MY FIRST WORD SERIES | PORTUGUESE - BRAZILIANS NURSERY RHYMES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-04",
    "orderNumber": "SP6105",
    "recipientName": "Joy Zamora",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS | TAGALOG - MY FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 8.54,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 13.28
  },
  {
    "shipDate": "2026-04-04",
    "orderNumber": "SP6106",
    "recipientName": "Cassie Sloan",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-04",
    "orderNumber": "SP6107",
    "recipientName": "Natalie Ducot",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES | SPANISH SONG BOOK - ANIMAL SONGS | SPANISH SONG BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-04",
    "orderNumber": "SP6108",
    "recipientName": "Jessica Chi",
    "itemNames": "KOREAN SONG BOOK - ANIMAL SONGS | KOREAN SONG BOOK - CHILDREN SONGS | KOREAN SONG BOOK - NURSERY RHYMES | KOREAN - FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 8.97,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 13.71
  },
  {
    "shipDate": "2026-04-04",
    "orderNumber": "SP6110",
    "recipientName": "Quvondo Johnson",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES | SPANISH SONG BOOK - ANIMAL SONGS | SPANISH SONG BOOK - CHILDREN SONGS | SPANISH - MY FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 6.96,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 11.7
  },
  {
    "shipDate": "2026-04-05",
    "orderNumber": "SP6111",
    "recipientName": "Maricel Mackie",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS | TAGALOG - MY FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 8.97,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 13.71
  },
  {
    "shipDate": "2026-04-05",
    "orderNumber": "SP6112",
    "recipientName": "Jason Nangan",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-05",
    "orderNumber": "SP6113",
    "recipientName": "Shawnie Fullford",
    "itemNames": "PORTUGUESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-05",
    "orderNumber": "SP6114",
    "recipientName": "Kristin Daro",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-05",
    "orderNumber": "SP6115",
    "recipientName": "Bianca Mirels",
    "itemNames": "PORTUGUESE - MY FIRST WORD SERIES | PORTUGUESE - BRAZILIANS NURSERY RHYMES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-05",
    "orderNumber": "SP6116",
    "recipientName": "Ro Marquez",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-05",
    "orderNumber": "SP6117",
    "recipientName": "Avery Loureiro",
    "itemNames": "PORTUGUESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-05",
    "orderNumber": "SP6119",
    "recipientName": "MADELINE SAPIANDANTE",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-05",
    "orderNumber": "SP6120",
    "recipientName": "Maya Kosiba",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-05",
    "orderNumber": "SP6121",
    "recipientName": "Jeannette Magsino",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6122",
    "recipientName": "Lindsey Larrabee",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES | SPANISH SONG BOOK - ANIMAL SONGS | SPANISH SONG BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6123",
    "recipientName": "Vanessa Wong",
    "itemNames": "PORTUGUESE - MY FIRST WORD SERIES | PORTUGUESE - BRAZILIANS NURSERY RHYMES",
    "qty": 2.0,
    "shippingTotal": 6.38,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 9.93
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6124",
    "recipientName": "Marister Wei",
    "itemNames": "PORTUGUESE - MY FIRST WORD SERIES | PORTUGUESE - BRAZILIANS NURSERY RHYMES",
    "qty": 2.0,
    "shippingTotal": 6.25,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 9.8
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6125",
    "recipientName": "Ronald Jay Tabago",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES",
    "qty": 1.0,
    "shippingTotal": 5.22,
    "boxName": "12x10x3",
    "pickpackTotal": 2.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 8.27
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6127",
    "recipientName": "Cosette Gabriel",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6128",
    "recipientName": "Jade Buhite",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6129",
    "recipientName": "Veena Trinh",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6130",
    "recipientName": "Bret Scofield",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES | SPANISH SONG BOOK - ANIMAL SONGS | SPANISH SONG BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6131",
    "recipientName": "Glenn Anderson",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES",
    "qty": 1.0,
    "shippingTotal": 5.22,
    "boxName": "12x10x3",
    "pickpackTotal": 2.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 8.27
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6132",
    "recipientName": "Jessica Cardoso Infante",
    "itemNames": "PORTUGUESE - BRAZILIANS NURSERY RHYMES",
    "qty": 1.0,
    "shippingTotal": 5.22,
    "boxName": "12x10x3",
    "pickpackTotal": 2.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 8.27
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6133",
    "recipientName": "Gustavo de Oliveira",
    "itemNames": "PORTUGUESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6134",
    "recipientName": "Silvana Cottiss",
    "itemNames": "PORTUGUESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6135",
    "recipientName": "Michelle Chin",
    "itemNames": "CHINESE - MY FIRST WORD SERIES [SIMPLIFIED]",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6136",
    "recipientName": "Alvin Salvanera",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS",
    "qty": 1.0,
    "shippingTotal": 5.22,
    "boxName": "12x10x3",
    "pickpackTotal": 2.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 8.27
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6137",
    "recipientName": "Samantha Patterson",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6138",
    "recipientName": "andrea hoang",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-07",
    "orderNumber": "SP6139",
    "recipientName": "Alecx Ortiz",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-08",
    "orderNumber": "SP6140",
    "recipientName": "Linh Kieu",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-08",
    "orderNumber": "SP6141",
    "recipientName": "Kyong Hong",
    "itemNames": "KOREAN SONG BOOK - NURSERY RHYMES",
    "qty": 1.0,
    "shippingTotal": 5.22,
    "boxName": "12x10x3",
    "pickpackTotal": 2.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 8.27
  },
  {
    "shipDate": "2026-04-08",
    "orderNumber": "SP6142",
    "recipientName": "Kim Vo",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-08",
    "orderNumber": "SP6145",
    "recipientName": "Alicia West",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES | TAGALOG SOUND BOOK - NURSERY RHYMES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-08",
    "orderNumber": "SP6146",
    "recipientName": "Richard Chung",
    "itemNames": "KOREAN - FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.92,
    "boxName": "",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.42
  },
  {
    "shipDate": "2026-04-08",
    "orderNumber": "SP6147",
    "recipientName": "Jacqueline Binady",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES | TAGALOG SOUND BOOK - NURSERY RHYMES",
    "qty": 1.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 2.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 9.77
  },
  {
    "shipDate": "2026-04-09",
    "orderNumber": "SP6148",
    "recipientName": "Shenyll Sumida",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-09",
    "orderNumber": "SP6149",
    "recipientName": "Tatiana Goldberg",
    "itemNames": "PORTUGUESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-09",
    "orderNumber": "SP6150",
    "recipientName": "Gisele De Lima Teixeira",
    "itemNames": "PORTUGUESE - BRAZILIANS NURSERY RHYMES",
    "qty": 1.0,
    "shippingTotal": 4.47,
    "boxName": "BUBBLE MAILER",
    "pickpackTotal": 2.5,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 7.17
  },
  {
    "shipDate": "2026-04-09",
    "orderNumber": "SP6152",
    "recipientName": "Ashley Frost-Layton",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-09",
    "orderNumber": "SP6153",
    "recipientName": "Dana Nguyen",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-09",
    "orderNumber": "SP6157",
    "recipientName": "jazmine and mario",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-09",
    "orderNumber": "SP6158",
    "recipientName": "Justine Nguyen",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-10",
    "orderNumber": "SP6159",
    "recipientName": "Sheila Nelson",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES | SPANISH SONG BOOK - ANIMAL SONGS | SPANISH SONG BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-10",
    "orderNumber": "SP6160",
    "recipientName": "Vance Belmonte",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-10",
    "orderNumber": "SP6161",
    "recipientName": "Ms Carolina Prudencio",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.38,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 9.93
  },
  {
    "shipDate": "2026-04-11",
    "orderNumber": "SP6162",
    "recipientName": "Chuck Huynh",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-11",
    "orderNumber": "SP6164",
    "recipientName": "Christine Aspiras",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.38,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 9.93
  },
  {
    "shipDate": "2026-04-11",
    "orderNumber": "SP6165",
    "recipientName": "Somi Jang",
    "itemNames": "KOREAN SONG BOOK - ANIMAL SONGS | KOREAN SONG BOOK - CHILDREN SONGS | KOREAN SONG BOOK - NURSERY RHYMES | KOREAN - FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 6.95,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 11.69
  },
  {
    "shipDate": "2026-04-11",
    "orderNumber": "SP6166",
    "recipientName": "Sean Moore",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-11",
    "orderNumber": "SP6167",
    "recipientName": "Lyle Ysip",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-12",
    "orderNumber": "SP6168",
    "recipientName": "Tiffani Bashagurova",
    "itemNames": "RUSSIAN - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-12",
    "orderNumber": "SP6169",
    "recipientName": "Alexa Salmon",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-12",
    "orderNumber": "SP6170",
    "recipientName": "Melissa Black",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES | CHINESE - MY FIRST WORD SERIES [SIMPLIFIED]",
    "qty": 2.0,
    "shippingTotal": 7.47,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 10.67
  },
  {
    "shipDate": "2026-04-12",
    "orderNumber": "SP6172",
    "recipientName": "Amy Sadler",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-12",
    "orderNumber": "SP6174",
    "recipientName": "Jaydog17 Phung",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-12",
    "orderNumber": "SP6175",
    "recipientName": "MICHELLE Dos ANJOS",
    "itemNames": "PORTUGUESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-12",
    "orderNumber": "SP6176",
    "recipientName": "Nora Hassanali",
    "itemNames": "PORTUGUESE - MY FIRST WORD SERIES | PORTUGUESE - BRAZILIANS NURSERY RHYMES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-12",
    "orderNumber": "SP6177",
    "recipientName": "Madel Aromin",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.25,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 9.8
  },
  {
    "shipDate": "2026-04-13",
    "orderNumber": "SP6179",
    "recipientName": "Matthew Drinkwater",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-13",
    "orderNumber": "SP6180",
    "recipientName": "Grace Louie",
    "itemNames": "CHINESE - MY FIRST WORD SERIES [SIMPLIFIED] | VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 7.47,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 10.47
  },
  {
    "shipDate": "2026-04-13",
    "orderNumber": "SP6181",
    "recipientName": "Juhayna Diaz",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.38,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.43
  },
  {
    "shipDate": "2026-04-13",
    "orderNumber": "SP6182",
    "recipientName": "Bruno Galvao",
    "itemNames": "PORTUGUESE - BRAZILIANS NURSERY RHYMES",
    "qty": 1.0,
    "shippingTotal": 4.47,
    "boxName": "BUBBLE MAILER",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 6.97
  },
  {
    "shipDate": "2026-04-13",
    "orderNumber": "SP6183",
    "recipientName": "Conrad Call",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES | VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.38,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 9.58
  },
  {
    "shipDate": "2026-04-13",
    "orderNumber": "SP6185",
    "recipientName": "Heather Pham",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-13",
    "orderNumber": "SP6186",
    "recipientName": "Michelle Peña",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-14",
    "orderNumber": "SP6187",
    "recipientName": "stephen kim",
    "itemNames": "KOREAN SONG BOOK - CHILDREN SONGS",
    "qty": 1.0,
    "shippingTotal": 5.22,
    "boxName": "BUBBLE MAILER",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 7.72
  },
  {
    "shipDate": "2026-04-14",
    "orderNumber": "SP6188",
    "recipientName": "leila kim",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.92,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.42
  },
  {
    "shipDate": "2026-04-14",
    "orderNumber": "SP6189",
    "recipientName": "Michelle Tran",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-15",
    "orderNumber": "SP6192",
    "recipientName": "Natalia Soares",
    "itemNames": "PORTUGUESE - MY FIRST WORD SERIES | PORTUGUESE - BRAZILIANS NURSERY RHYMES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-15",
    "orderNumber": "SP6193",
    "recipientName": "Linda Tran",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 7.47,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 10.67
  },
  {
    "shipDate": "2026-04-15",
    "orderNumber": "SP6194",
    "recipientName": "Kim Nguyen",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-15",
    "orderNumber": "SP6195",
    "recipientName": "ZERLAINE WILCOXEN",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-15",
    "orderNumber": "SP5884",
    "recipientName": "Ruth Reagan  [RESHIP FROM 3/10]",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 0.0,
    "boxName": "AS IS",
    "pickpackTotal": 0.0,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 0.0
  },
  {
    "shipDate": "2026-04-15",
    "orderNumber": "SP6196",
    "recipientName": "Raisa Brown",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.38,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 9.93
  },
  {
    "shipDate": "2026-04-15",
    "orderNumber": "SP6199",
    "recipientName": "Tracy Tran",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-15",
    "orderNumber": "SP6200",
    "recipientName": "Darlene and Josh Machacon",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 0.0,
    "boxName": "[UNIT #?]",
    "pickpackTotal": 0.0,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 0.0
  },
  {
    "shipDate": "2026-04-15",
    "orderNumber": "SP6201",
    "recipientName": "Julie Vo",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-15",
    "orderNumber": "SP6202",
    "recipientName": "Nga Everett",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-16",
    "orderNumber": "SP6203",
    "recipientName": "jaira ignacio",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-16",
    "orderNumber": "SP6204",
    "recipientName": "Kris Cox",
    "itemNames": "KOREAN SONG BOOK - ANIMAL SONGS | KOREAN SONG BOOK - CHILDREN SONGS | KOREAN SONG BOOK - NURSERY RHYMES | KOREAN - FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 8.97,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 13.71
  },
  {
    "shipDate": "2026-04-16",
    "orderNumber": "SP6205",
    "recipientName": "Jerry Salvo",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-16",
    "orderNumber": "SP6188",
    "recipientName": "leila kim",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 0.0,
    "boxName": "[RESHIP FROM 4/14]",
    "pickpackTotal": 0.0,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 0.0
  },
  {
    "shipDate": "2026-04-16",
    "orderNumber": "SP6207",
    "recipientName": "Cyrus Corpus",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.38,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.43
  },
  {
    "shipDate": "2026-04-16",
    "orderNumber": "SP6208",
    "recipientName": "Terese Martin",
    "itemNames": "SPANISH - MY FIRST WORD SERIES | VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 8.22,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 11.42
  },
  {
    "shipDate": "2026-04-16",
    "orderNumber": "SP6209",
    "recipientName": "Jackie Nguyen",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES | KOREAN - FIRST WORD SERIES | KOREAN SONG BOOK - NURSERY RHYMES",
    "qty": 3.0,
    "shippingTotal": 8.22,
    "boxName": "11x9x6",
    "pickpackTotal": 3.5,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 12.46
  },
  {
    "shipDate": "2026-04-16",
    "orderNumber": "SP6210",
    "recipientName": "Maureen Villaluz",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS | TAGALOG - MY FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 6.95,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 11.69
  },
  {
    "shipDate": "2026-04-16",
    "orderNumber": "SP6211",
    "recipientName": "Cassandra Ly",
    "itemNames": "CHINESE - MY FIRST WORD SERIES [TRADITIONAL]",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-16",
    "orderNumber": "SP6213",
    "recipientName": "Anya Lam",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.92,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.42
  },
  {
    "shipDate": "2026-04-17",
    "orderNumber": "SP6215",
    "recipientName": "Maggie Poyhanya",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-17",
    "orderNumber": "SP6216",
    "recipientName": "Caity Dietz",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG - MY FIRST WORD SERIES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 3.0,
    "shippingTotal": 8.22,
    "boxName": "11x9x6",
    "pickpackTotal": 3.5,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 12.46
  },
  {
    "shipDate": "2026-04-18",
    "orderNumber": "SP6217",
    "recipientName": "Keisha Lavatai",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-18",
    "orderNumber": "SP6218",
    "recipientName": "Issa Mendez",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES | SPANISH - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-18",
    "orderNumber": "SP6219",
    "recipientName": "Amanda Pham",
    "itemNames": "SPANISH - MY FIRST WORD SERIES | VIETNAMESE - MY FIRST WORD SERIES | KOREAN - FIRST WORD SERIES",
    "qty": 3.0,
    "shippingTotal": 5.92,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.5,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 9.62
  },
  {
    "shipDate": "2026-04-18",
    "orderNumber": "SP6225",
    "recipientName": "Baby Legaspi",
    "itemNames": "TAGALOG SOUND BOOK - CHILDREN SONGS",
    "qty": 1.0,
    "shippingTotal": 5.22,
    "boxName": "BUBBLE MAILER",
    "pickpackTotal": 2.5,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 7.92
  },
  {
    "shipDate": "2026-04-18",
    "orderNumber": "SP6266",
    "recipientName": "Leana Padilla",
    "itemNames": "SPANISH - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-18",
    "orderNumber": "SP6267",
    "recipientName": "Barry and Delena Mulingtapang",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 5.92,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 9.12
  },
  {
    "shipDate": "2026-04-18",
    "orderNumber": "SP6268",
    "recipientName": "Katrina Spenst-Jae",
    "itemNames": "KOREAN SONG BOOK - NURSERY RHYMES | KOREAN - FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-18",
    "orderNumber": "SP6269",
    "recipientName": "Stephanie Gant",
    "itemNames": "KOREAN SONG BOOK - NURSERY RHYMES",
    "qty": 1.0,
    "shippingTotal": 4.47,
    "boxName": "BUBBLE MAILER",
    "pickpackTotal": 2.5,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 7.17
  },
  {
    "shipDate": "2026-04-19",
    "orderNumber": "SP6270",
    "recipientName": "Ashley Huynh",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES | VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 7.47,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 10.67
  },
  {
    "shipDate": "2026-04-19",
    "orderNumber": "SP6271",
    "recipientName": "Pamela Brown",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES | SPANISH - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-19",
    "orderNumber": "SP6272",
    "recipientName": "Anna Salsbury",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS | TAGALOG - MY FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 8.94,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 13.68
  },
  {
    "shipDate": "2026-04-19",
    "orderNumber": "SP6273",
    "recipientName": "Dolly Padilla",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 0.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.0,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 7.97
  },
  {
    "shipDate": "2026-04-19",
    "orderNumber": "SP6286",
    "recipientName": "Joanna Aguirre",
    "itemNames": "SPANISH - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-19",
    "orderNumber": "SP6295",
    "recipientName": "Denise Antoku",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-19",
    "orderNumber": "SP6301",
    "recipientName": "Tram Tran",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-19",
    "orderNumber": "SP6317",
    "recipientName": "Vanessa Santiago",
    "itemNames": "SPANISH - MY FIRST WORD SERIES | SPANISH SONG BOOK - NURSERY RHYMES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-19",
    "orderNumber": "SP6324",
    "recipientName": "Kristine Truong",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-19",
    "orderNumber": "SP6326",
    "recipientName": "James Chang",
    "itemNames": "KOREAN SONG BOOK - CHILDREN SONGS",
    "qty": 1.0,
    "shippingTotal": 5.22,
    "boxName": "BUBBLE MAILER",
    "pickpackTotal": 2.5,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 7.92
  },
  {
    "shipDate": "2026-04-20",
    "orderNumber": "SP6327",
    "recipientName": "Erin Soriano",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.25,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 9.8
  },
  {
    "shipDate": "2026-04-20",
    "orderNumber": "SP6328",
    "recipientName": "Tuyet Nguyen",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-20",
    "orderNumber": "SP6329",
    "recipientName": "Administrator Administrator",
    "itemNames": "SPANISH - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-20",
    "orderNumber": "SP6330",
    "recipientName": "Joan Cardenas",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-20",
    "orderNumber": "SP6331",
    "recipientName": "Stephanie Nguyen",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-20",
    "orderNumber": "SP6332",
    "recipientName": "Tianna Alberts",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-20",
    "orderNumber": "SP6334",
    "recipientName": "Myjeil Villasin",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-20",
    "orderNumber": "SP6335",
    "recipientName": "Lorena Trevino",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES | SPANISH SONG BOOK - ANIMAL SONGS | SPANISH SONG BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-20",
    "orderNumber": "SP6336",
    "recipientName": "Kate Nelson",
    "itemNames": "TAGALOG SOUND BOOK - CHILDREN SONGS",
    "qty": 1.0,
    "shippingTotal": 5.22,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 7.72
  },
  {
    "shipDate": "2026-04-20",
    "orderNumber": "SP6337",
    "recipientName": "Mildred Polanco",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES | SPANISH SONG BOOK - NURSERY RHYMES",
    "qty": 2.0,
    "shippingTotal": 5.97,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 9.52
  },
  {
    "shipDate": "2026-04-20",
    "orderNumber": "SP6338",
    "recipientName": "Mahal Smith",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-21",
    "orderNumber": "SP6341",
    "recipientName": "Vien Nguyen",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-21",
    "orderNumber": "SP6342",
    "recipientName": "Brittany Bujacich",
    "itemNames": "KOREAN SONG BOOK - NURSERY RHYMES | KOREAN - FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-21",
    "orderNumber": "SP6344",
    "recipientName": "Kelly Flynn",
    "itemNames": "KOREAN SONG BOOK - NURSERY RHYMES | KOREAN - FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-21",
    "orderNumber": "SP6346",
    "recipientName": "Elise Kreider",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES | SPANISH - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-21",
    "orderNumber": "SP6347",
    "recipientName": "Julian Amadei",
    "itemNames": "KOREAN SONG BOOK - ANIMAL SONGS | KOREAN SONG BOOK - CHILDREN SONGS | KOREAN SONG BOOK - NURSERY RHYMES",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-21",
    "orderNumber": "SP6348",
    "recipientName": "Colleen Ly",
    "itemNames": "CHINESE - MY FIRST WORD SERIES [TRADITIONAL]",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-22",
    "orderNumber": "SP6349",
    "recipientName": "Mari Huerta",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES | SPANISH SONG BOOK - ANIMAL SONGS | SPANISH SONG BOOK - CHILDREN SONGS | SPANISH - MY FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 7.68,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 12.42
  },
  {
    "shipDate": "2026-04-22",
    "orderNumber": "SP6350",
    "recipientName": "Nicole Czajkowski",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-22",
    "orderNumber": "SP6352",
    "recipientName": "Kate Parsons",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - CHILDREN SONGS",
    "qty": 2.0,
    "shippingTotal": 5.97,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 9.52
  },
  {
    "shipDate": "2026-04-22",
    "orderNumber": "SP6354",
    "recipientName": "Lauren Satalia",
    "itemNames": "KOREAN - FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-22",
    "orderNumber": "SP6356",
    "recipientName": "Jessica Boswell",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-22",
    "orderNumber": "SP6357",
    "recipientName": "Angeline Tran",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-22",
    "orderNumber": "SP6358",
    "recipientName": "Jasmine Deedy",
    "itemNames": "KOREAN SONG BOOK - NURSERY RHYMES | KOREAN - FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-22",
    "orderNumber": "SP6359",
    "recipientName": "Chello French",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-22",
    "orderNumber": "SP6360",
    "recipientName": "Michelle Wingfield",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-23",
    "orderNumber": "SP6361",
    "recipientName": "Rachel Medina",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES | SPANISH SONG BOOK - ANIMAL SONGS | SPANISH SONG BOOK - CHILDREN SONGS | SPANISH - MY FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 8.97,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 13.71
  },
  {
    "shipDate": "2026-04-23",
    "orderNumber": "SP6362",
    "recipientName": "Erik Diaz",
    "itemNames": "SPANISH - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-23",
    "orderNumber": "SP6363",
    "recipientName": "Dianna Enriquez Vo",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-23",
    "orderNumber": "SP6364",
    "recipientName": "Cherlyn Medina",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES",
    "qty": 1.0,
    "shippingTotal": 5.22,
    "boxName": "BUBBLE MAILER",
    "pickpackTotal": 2.5,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 7.92
  },
  {
    "shipDate": "2026-04-23",
    "orderNumber": "SP6365",
    "recipientName": "Emmanuel Manaois",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-23",
    "orderNumber": "SP6366",
    "recipientName": "Kimberly Rabang",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES | KOREAN - FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 7.47,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 10.67
  },
  {
    "shipDate": "2026-04-23",
    "orderNumber": "SP6367",
    "recipientName": "Stephanie Diaz",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES | SPANISH SONG BOOK - ANIMAL SONGS | SPANISH SONG BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-23",
    "orderNumber": "SP6368",
    "recipientName": "Meghan McAfee",
    "itemNames": "KOREAN SONG BOOK - ANIMAL SONGS | KOREAN SONG BOOK - CHILDREN SONGS | KOREAN SONG BOOK - NURSERY RHYMES",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-23",
    "orderNumber": "SP6369",
    "recipientName": "YOUNGLEE HAN",
    "itemNames": "KOREAN SONG BOOK - ANIMAL SONGS | KOREAN SONG BOOK - CHILDREN SONGS | KOREAN SONG BOOK - NURSERY RHYMES",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-24",
    "orderNumber": "SP6370",
    "recipientName": "Rachel Cox",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-24",
    "orderNumber": "SP6371",
    "recipientName": "Crisfer Fernandez-Reyes",
    "itemNames": "SPANISH - MY FIRST WORD SERIES | VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 7.47,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 10.67
  },
  {
    "shipDate": "2026-04-24",
    "orderNumber": "SP6372",
    "recipientName": "Alysson Corrales",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES | SPANISH SONG BOOK - ANIMAL SONGS | SPANISH SONG BOOK - CHILDREN SONGS | SPANISH - MY FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 8.97,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 13.71
  },
  {
    "shipDate": "2026-04-24",
    "orderNumber": "SP6373",
    "recipientName": "Maria Adriana Davis",
    "itemNames": "SPANISH SONG BOOK - CHILDREN SONGS",
    "qty": 1.0,
    "shippingTotal": 5.22,
    "boxName": "BUBBLE MAILER",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 7.72
  },
  {
    "shipDate": "2026-04-24",
    "orderNumber": "SP6189",
    "recipientName": "Michelle Tran",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 0.0,
    "boxName": "[RESHIP FROM 4/14]",
    "pickpackTotal": 0.0,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 0.0
  },
  {
    "shipDate": "2026-04-24",
    "orderNumber": "SP6374",
    "recipientName": "Lesley Magno",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.92,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.42
  },
  {
    "shipDate": "2026-04-24",
    "orderNumber": "SP6375",
    "recipientName": "Rachel Garcia",
    "itemNames": "KOREAN SONG BOOK - ANIMAL SONGS | KOREAN SONG BOOK - CHILDREN SONGS | KOREAN SONG BOOK - NURSERY RHYMES | KOREAN - FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 8.97,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 13.71
  },
  {
    "shipDate": "2026-04-24",
    "orderNumber": "SP6376",
    "recipientName": "Sarah Worth",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG - MY FIRST WORD SERIES | SPANISH - MY FIRST WORD SERIES",
    "qty": 3.0,
    "shippingTotal": 6.96,
    "boxName": "11x9x6",
    "pickpackTotal": 3.5,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 11.2
  },
  {
    "shipDate": "2026-04-24",
    "orderNumber": "SP6377",
    "recipientName": "Summer Chitwood",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-24",
    "orderNumber": "SP6378",
    "recipientName": "Marie Boney",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-24",
    "orderNumber": "SP6379",
    "recipientName": "Jennifer Palmer",
    "itemNames": "KOREAN SONG BOOK - NURSERY RHYMES | KOREAN - FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.38,
    "boxName": "11x9x6",
    "pickpackTotal": 3.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 10.12
  },
  {
    "shipDate": "2026-04-24",
    "orderNumber": "SP6380",
    "recipientName": "Alexandria Lieu",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.78,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 9.98
  },
  {
    "shipDate": "2026-04-24",
    "orderNumber": "SP6381",
    "recipientName": "Quynh Duong",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-24",
    "orderNumber": "SP6382",
    "recipientName": "Jacqueline Gonzales",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES | SPANISH - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.8,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 10.0
  },
  {
    "shipDate": "2026-04-25",
    "orderNumber": "SP6384",
    "recipientName": "Maxine Aponte-DeKleva",
    "itemNames": "SPANISH - MY FIRST WORD SERIES",
    "qty": 0.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.0,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 7.97
  },
  {
    "shipDate": "2026-04-25",
    "orderNumber": "SP6385",
    "recipientName": "Timothy Kang",
    "itemNames": "KOREAN SONG BOOK - NURSERY RHYMES",
    "qty": 1.0,
    "shippingTotal": 4.47,
    "boxName": "BUBBLE MAILER",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 6.97
  },
  {
    "shipDate": "2026-04-25",
    "orderNumber": "SP6386",
    "recipientName": "Hana Lehmann",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS",
    "qty": 1.0,
    "shippingTotal": 4.47,
    "boxName": "BUBBLE MAILER",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 6.97
  },
  {
    "shipDate": "2026-04-25",
    "orderNumber": "SP6387",
    "recipientName": "Martha Castro",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES",
    "qty": 1.0,
    "shippingTotal": 4.47,
    "boxName": "BUBBLE MAILER",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 6.97
  },
  {
    "shipDate": "2026-04-25",
    "orderNumber": "SP6388",
    "recipientName": "Laura Favazza",
    "itemNames": "PORTUGUESE - BRAZILIANS NURSERY RHYMES | PORTUGUESE - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-25",
    "orderNumber": "SP6389",
    "recipientName": "Michelle Nafarrete",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - CHILDREN SONGS",
    "qty": 2.0,
    "shippingTotal": 5.97,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 9.52
  },
  {
    "shipDate": "2026-04-25",
    "orderNumber": "SP6390",
    "recipientName": "Franchi German",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES | TAGALOG SOUND BOOK - NURSERY RHYMES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-25",
    "orderNumber": "SP6391",
    "recipientName": "Vicky Tu",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.92,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.42
  },
  {
    "shipDate": "2026-04-26",
    "orderNumber": "SP6392",
    "recipientName": "ramon sinsuan jr",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS | TAGALOG - MY FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 7.16,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 11.9
  },
  {
    "shipDate": "2026-04-26",
    "orderNumber": "SP6393",
    "recipientName": "Nina DiPerrio",
    "itemNames": "KOREAN - FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-26",
    "orderNumber": "SP6394",
    "recipientName": "Ameera Sheikh",
    "itemNames": "ARABIC - FIRST WORD SERIES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 7.47,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 10.67
  },
  {
    "shipDate": "2026-04-26",
    "orderNumber": "SP6395",
    "recipientName": "Brittney Kow",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES | SPANISH SONG BOOK - ANIMAL SONGS | SPANISH SONG BOOK - CHILDREN SONGS | SPANISH - MY FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 8.97,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 13.71
  },
  {
    "shipDate": "2026-04-26",
    "orderNumber": "SP6397",
    "recipientName": "Alex Alex",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-26",
    "orderNumber": "SP6398",
    "recipientName": "Caitlin Halloran",
    "itemNames": "KOREAN - FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-26",
    "orderNumber": "SP6399",
    "recipientName": "Leilani Magdaleno",
    "itemNames": "SPANISH SONG BOOK - NURSERY RHYMES | SPANISH SONG BOOK - ANIMAL SONGS | SPANISH SONG BOOK - CHILDREN SONGS | SPANISH - MY FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 8.97,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 13.71
  },
  {
    "shipDate": "2026-04-26",
    "orderNumber": "SP6400",
    "recipientName": "Anngelie Spoor",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-27",
    "orderNumber": "SP6401",
    "recipientName": "Christine Guiao",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-27",
    "orderNumber": "SP6402",
    "recipientName": "Carla Minaya",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES | SPANISH - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 7.47,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 10.67
  },
  {
    "shipDate": "2026-04-27",
    "orderNumber": "SP6403",
    "recipientName": "Marge Hart",
    "itemNames": "PORTUGUESE - BRAZILIANS NURSERY RHYMES | PORTUGUESE - MY FIRST WORD SERIES | PORTUGUESE - MY FIRST WORD SERIES",
    "qty": 3.0,
    "shippingTotal": 8.22,
    "boxName": "11x9x6",
    "pickpackTotal": 3.5,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 12.46
  },
  {
    "shipDate": "2026-04-27",
    "orderNumber": "SP6405",
    "recipientName": "Sheila Valdez",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-27",
    "orderNumber": "SP6407",
    "recipientName": "Anya Fong",
    "itemNames": "RUSSIAN - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-27",
    "orderNumber": "SP6408",
    "recipientName": "Hannah Clarke",
    "itemNames": "CHINESE - MY FIRST WORD SERIES [SIMPLIFIED]",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-27",
    "orderNumber": "SP6409",
    "recipientName": "Ericah Ellick",
    "itemNames": "SPANISH - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-27",
    "orderNumber": "SP6410",
    "recipientName": "Eddie Medallo",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-27",
    "orderNumber": "SP6411",
    "recipientName": "Jenny Yanez",
    "itemNames": "SPANISH - MY FIRST WORD SERIES | KOREAN - FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.25,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 9.45
  },
  {
    "shipDate": "2026-04-28",
    "orderNumber": "SP6413",
    "recipientName": "RACHEL NAM",
    "itemNames": "KOREAN SONG BOOK - ANIMAL SONGS | KOREAN SONG BOOK - CHILDREN SONGS | KOREAN SONG BOOK - NURSERY RHYMES",
    "qty": 3.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.5,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.77
  },
  {
    "shipDate": "2026-04-28",
    "orderNumber": "SP6414",
    "recipientName": "Rebeca Cuellar",
    "itemNames": "SPANISH - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-28",
    "orderNumber": "SP6415",
    "recipientName": "Marissa Joy Agbunag",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS | TAGALOG - MY FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 8.97,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 13.71
  },
  {
    "shipDate": "2026-04-28",
    "orderNumber": "SP6416",
    "recipientName": "Sarah Domingo",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-28",
    "orderNumber": "SP6417",
    "recipientName": "Guila Rodhouse",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS | TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 8.97,
    "boxName": "11x9x6",
    "pickpackTotal": 2.5,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 12.21
  },
  {
    "shipDate": "2026-04-28",
    "orderNumber": "SP6418",
    "recipientName": "Alicia West",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - CHILDREN SONGS",
    "qty": 2.0,
    "shippingTotal": 5.97,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 9.52
  },
  {
    "shipDate": "2026-04-28",
    "orderNumber": "SP6420",
    "recipientName": "Hayley McSwain",
    "itemNames": "SPANISH SONG BOOK - CHILDREN SONGS",
    "qty": 1.0,
    "shippingTotal": 4.47,
    "boxName": "BUBBLE MAILER",
    "pickpackTotal": 2.5,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 7.17
  },
  {
    "shipDate": "2026-04-28",
    "orderNumber": "SP6421",
    "recipientName": "Mina Le",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-28",
    "orderNumber": "SP6422",
    "recipientName": "YJ Her",
    "itemNames": "KOREAN SONG BOOK - ANIMAL SONGS | KOREAN SONG BOOK - CHILDREN SONGS",
    "qty": 2.0,
    "shippingTotal": 5.97,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 9.52
  },
  {
    "shipDate": "2026-04-28",
    "orderNumber": "SP6423",
    "recipientName": "Kay Seals",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS | TAGALOG - MY FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 7.16,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 11.9
  },
  {
    "shipDate": "2026-04-29",
    "orderNumber": "SP6425",
    "recipientName": "Maria Belleza",
    "itemNames": "TAGALOG - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-29",
    "orderNumber": "SP6426",
    "recipientName": "Diemkieu Geditz",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-29",
    "orderNumber": "SP6428",
    "recipientName": "Lyndenne Ccg",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES",
    "qty": 2.0,
    "shippingTotal": 5.97,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 9.52
  },
  {
    "shipDate": "2026-04-29",
    "orderNumber": "SP6429",
    "recipientName": "Petrina Joe-Lanhan",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-29",
    "orderNumber": "SP6430",
    "recipientName": "Hanna Tran",
    "itemNames": "CHINESE - MY FIRST WORD SERIES [TRADITIONAL]CANCELLED",
    "qty": 1.0,
    "shippingTotal": 0.0,
    "boxName": "",
    "pickpackTotal": 0.0,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 0.0
  },
  {
    "shipDate": "2026-04-29",
    "orderNumber": "SP6431",
    "recipientName": "Bennet Samson",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-30",
    "orderNumber": "SP6433",
    "recipientName": "Madeline Hughes",
    "itemNames": "TAGALOG SOUND BOOK - ANIMAL SONGS | TAGALOG SOUND BOOK - NURSERY RHYMES | TAGALOG SOUND BOOK - CHILDREN SONGS | TAGALOG - MY FIRST WORD SERIES",
    "qty": 4.0,
    "shippingTotal": 7.68,
    "boxName": "11x9x6",
    "pickpackTotal": 4.0,
    "packageTotal": 0.74,
    "storageTotal": 0.0,
    "rowTotal": 12.42
  },
  {
    "shipDate": "2026-04-30",
    "orderNumber": "SP6434",
    "recipientName": "Rachel Tai",
    "itemNames": "CHINESE - MY FIRST WORD SERIES [TRADITIONAL] | VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 7.47,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 10.67
  },
  {
    "shipDate": "2026-04-30",
    "orderNumber": "SP6435",
    "recipientName": "Connie Amado",
    "itemNames": "TAGALOG SOUND BOOK - NURSERY RHYMES",
    "qty": 1.0,
    "shippingTotal": 4.47,
    "boxName": "BUBBLE MAILER",
    "pickpackTotal": 2.5,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 7.17
  },
  {
    "shipDate": "2026-04-30",
    "orderNumber": "SP6436",
    "recipientName": "Chloe Ho",
    "itemNames": "KOREAN - FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 7.18,
    "boxName": "[EXPRESS SHIPPING]",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 9.68
  },
  {
    "shipDate": "2026-04-30",
    "orderNumber": "SP6437",
    "recipientName": "Jina Huynh",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES | SPANISH - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 7.47,
    "boxName": "AS IS + POLY",
    "pickpackTotal": 3.0,
    "packageTotal": 0.2,
    "storageTotal": 0.0,
    "rowTotal": 10.67
  },
  {
    "shipDate": "2026-04-30",
    "orderNumber": "SP6438",
    "recipientName": "Kimberly Huatran",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 0.0,
    "rowTotal": 8.47
  },
  {
    "shipDate": "2026-04-30",
    "orderNumber": "SP6439",
    "recipientName": "Katherine Ling",
    "itemNames": "PORTUGUESE - BRAZILIANS NURSERY RHYMES | PORTUGUESE - MY FIRST WORD SERIES",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-30",
    "orderNumber": "SP6440",
    "recipientName": "Carmina Estranero",
    "itemNames": "JOEY BOOKS - LEARNING SONGS | SPANISH SONG BOOK - CHILDREN SONGS",
    "qty": 2.0,
    "shippingTotal": 6.72,
    "boxName": "12x10x3",
    "pickpackTotal": 3.0,
    "packageTotal": 0.55,
    "storageTotal": 0.0,
    "rowTotal": 10.27
  },
  {
    "shipDate": "2026-04-30",
    "orderNumber": "SP6441",
    "recipientName": "Dung Merrikh",
    "itemNames": "VIETNAMESE - MY FIRST WORD SERIES",
    "qty": 1.0,
    "shippingTotal": 5.97,
    "boxName": "AS IS",
    "pickpackTotal": 2.5,
    "packageTotal": 0.0,
    "storageTotal": 63.34,
    "rowTotal": 71.81
  }
];

export function heritagePrepFeeRowsForRange(dateFrom: string, dateTo: string) {
  const from = dateFrom.slice(0, 10);
  const to = dateTo.slice(0, 10);
  return HERITAGE_PREP_FEE_OVERRIDES.filter((row) => row.shipDate >= from && row.shipDate <= to);
}
