/**
 * CP-059 — the Client Portal boundary must accept everything PrepShip actually emits.
 *
 * THIS GUARD EXISTS BECAUSE THE SAME MISTAKE HAPPENED TWICE. CP-059 failed exact-SHA review
 * twice for one reason: this repository encoded a guess about PrepShip's contract, its own
 * hand-written fixtures agreed with the guess, and four green CI lanes proved only that the
 * portal agreed with itself.
 *
 *   1. The boundary rejected `hasReturnPostageLine: false` with a numeric `0`. That is the
 *      producer's normal absent-fee shape and it is on EVERY row, so the Billing view would
 *      have returned 502 for every request.
 *   2. The boundary required a non-null `orderId`. PrepShip emits storage lines with
 *      `orderId: null` by design, so any period containing storage billing returned 502.
 *
 * Neither was catchable here, because the contract was written down nowhere both repositories
 * could see. So it is written down now: `fixtures/cp-059-producer-billing-rows.json` is
 * GENERATED by PrepShip's real `toBillingDetailOrderRows`, committed, and asserted against here.
 * The portal no longer gets a vote on what the producer emits.
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

process.env.PREPSHIP_API_URL ??= 'http://canonical.test';
process.env.DATABASE_URL ??= 'postgres://u:p@127.0.0.1:5432/unused';
process.env.SUPABASE_JWT_SECRET ??= 'cp059-producer-guard';
process.env.NODE_ENV ??= 'test';

const { toCanonicalBillingEventRow, fetchCanonicalBillingDetails } =
  await import('../src/lib/client-portal/prepship-billing-details-proxy.js');
const { renderPortalInvoiceHtml } = await import('../src/lib/client-portal/invoice-html.js');
const { buildInvoiceExcelSheet } = await import('../portal-client/src/lib/invoiceExcel.js');

let checks = 0;
const ok = (label: string) => { checks += 1; console.log(`ok   ${label}`); };

const FIXTURE = 'fixtures/cp-059-producer-billing-rows.json';
const fixture = JSON.parse(readFileSync(FIXTURE, 'utf8')) as {
  producerSha: string;
  shapes: Array<{ name: string; rows: Array<Record<string, unknown>> }>;
};

// Provenance. A fixture with no recorded producer SHA is a fixture nobody can trace back to the
// code that produced it, which is how a stale contract survives unnoticed.
assert.match(fixture.producerSha, /^[0-9a-f]{40}$/, 'the fixture must record the producer SHA it came from');
assert.ok(fixture.shapes.length >= 11, `expected at least 11 producer shapes, got ${fixture.shapes.length}`);
console.log(`     producer SHA ${fixture.producerSha}, ${fixture.shapes.length} shapes`);
ok('the committed producer fixture records its provenance and covers every known shape');

// --- 1. EVERY producer row is accepted -------------------------------------------------------

const rejected: string[] = [];
const accepted: Array<Record<string, unknown>> = [];
for (const shape of fixture.shapes) {
  for (const row of shape.rows) {
    const mapped = toCanonicalBillingEventRow(row);
    if (mapped === null) rejected.push(shape.name);
    else accepted.push(mapped as unknown as Record<string, unknown>);
  }
}
assert.deepEqual(
  rejected, [],
  `the boundary rejected shapes PrepShip actually emits: ${[...new Set(rejected)].join(' | ')}\n`
  + 'A rejected row fails the WHOLE response, so each of these is a 502 for every period that '
  + 'contains one.',
);
ok(`all ${accepted.length} producer rows are accepted by the boundary`);

// The orderless storage rows specifically — the shape that caused the last failure.
const storageRows = accepted.filter((r) => r.orderId === null);
assert.ok(storageRows.length >= 3, `expected the orderless storage rows to survive, got ${storageRows.length}`);
ok(`${storageRows.length} ORDERLESS storage rows survive the boundary`);

// --- 2. identity is carried, and separates rows the old key collapsed ------------------------

for (const row of accepted) {
  assert.equal(typeof row.canonicalEventId, 'string', 'every accepted row carries the producer identity');
  assert.ok(String(row.canonicalEventId).length > 0, 'and it is never empty');
}
const ids = accepted.map((r) => String(r.canonicalEventId));
assert.equal(new Set(ids).size, ids.length, 'producer identities must stay distinct through the boundary');
ok('the producer identity is carried verbatim and stays distinct for every row');

// The two storage lines sharing a description are the case that used to collapse. Under the old
// key — orderId|returnId|rowType — both were `||Outbound`.
const twoStorage = fixture.shapes.find((s) => s.name.startsWith('TWO orderless storage'))!;
const twoMapped = twoStorage.rows.map((r) => toCanonicalBillingEventRow(r) as unknown as Record<string, unknown>);
assert.equal(twoMapped.length, 2, 'both storage rows must map');
const legacyKey = (r: Record<string, unknown>) => `${r.orderId ?? ''}|${r.returnId ?? ''}|${r.rowType ?? ''}`;
assert.equal(
  legacyKey(twoMapped[0]), legacyKey(twoMapped[1]),
  'setup check: the OLD key really did collapse these two rows — otherwise the next assertion proves nothing',
);
assert.notEqual(
  twoMapped[0].canonicalEventId, twoMapped[1].canonicalEventId,
  'two storage lines sharing a description must be distinguishable by the producer identity',
);
ok('two storage rows that the old key collapsed are separated by the producer identity');

// --- 3. no producer row renders fabricated money ---------------------------------------------

const html = renderPortalInvoiceHtml({
  clientName: 'Acme Fulfilment', dateFrom: '2026-08-01', dateTo: '2026-08-31',
  details: accepted as never, truncated: false,
  invoiceTotals: {
    orderCount: accepted.length, qty: 0, pickPackTotal: 0, additionalTotal: 0, packageTotal: 0,
    shippingTotal: 0, storageTotal: 0, grandTotal: 0,
  },
});
const bodyRows = (html.match(/<tbody>[\s\S]*?<\/tbody>/) ?? [''])[0]
  .split('</tr>').filter((c) => c.includes('<td'));
assert.equal(bodyRows.length, accepted.length, `every accepted row must render (${bodyRows.length} vs ${accepted.length})`);

// A row whose return fee is ABSENT must blank both return cells, whatever amount it carries.
const HTML_PROCESSING = 12;
const HTML_POSTAGE = 13;
for (const [index, row] of accepted.entries()) {
  const cells = [...bodyRows[index].matchAll(/<td[^>]*>([\s\S]*?)<\/td>/g)].map((m) => m[1].trim());
  assert.equal(cells.length, 15, `row ${index} rendered ${cells.length} cells`);
  if (row.hasReturnPostageLine === false) {
    assert.equal(cells[HTML_POSTAGE], '&mdash;',
      `an absent postage line must blank, not print the ${row.returnPostageTotal} it carries`);
  }
  if (row.hasReturnProcessingLine === false) {
    assert.equal(cells[HTML_PROCESSING], '&mdash;',
      `an absent processing line must blank, not print the ${row.returnProcessingTotal} it carries`);
  }
}
ok('no producer row prints a fabricated $0.00 in the printable invoice');

const { sheet } = buildInvoiceExcelSheet(accepted as never);
assert.equal(sheet.length, accepted.length + 2, 'header + every row + totals');
ok('every producer row survives into the spreadsheet export');

// --- 4. the whole fixture passes through the response boundary as one payload -----------------

const originalFetch = globalThis.fetch;
globalThis.fetch = (async () => new Response(
  JSON.stringify({ data: fixture.shapes.flatMap((s) => s.rows) }),
  { status: 200, headers: { 'content-type': 'application/json' } },
)) as typeof fetch;
const whole = await fetchCanonicalBillingDetails('Bearer t', { dateFrom: '2026-08-01', dateTo: '2026-09-01' });
globalThis.fetch = originalFetch;
assert.ok(whole.ok, `the full producer payload must not fail the response boundary: ${whole.ok ? '' : whole.code}`);
assert.equal(whole.rows.length, accepted.length, 'every producer row survives the response boundary');
ok('the entire producer payload passes the response boundary in one piece');

const EXPECTED_CHECKS = 8;
assert.equal(checks, EXPECTED_CHECKS, `expected ${EXPECTED_CHECKS} checks; ${checks} ran`);
console.log('');
console.log(`PASS CP-059 producer contract guard - ${checks}/${EXPECTED_CHECKS} checks`);
