/**
 * CP-059 — the Client Portal boundary must accept everything PrepShip actually emits.
 *
 * THIS GUARD EXISTS BECAUSE THE SAME MISTAKE HAPPENED TWICE. CP-059 failed exact-SHA review
 * twice for one reason: this repository encoded a guess about PrepShip's contract, its own
 * hand-written fixtures agreed with the guess, and four green CI lanes proved only that the
 * portal agreed with itself.
 *
 *   1. The boundary rejected `hasReturnPostageLine: false` with a numeric `0`. That is the
 *      producer's normal absent-fee shape and it is on EVERY row, so the Billing view would
 *      have returned 502 for every request.
 *   2. The boundary required a non-null `orderId`. PrepShip emits storage lines with
 *      `orderId: null` by design, so any period containing storage billing returned 502.
 *
 * Neither was catchable here, because the contract was written down nowhere both repositories
 * could see. So it is written down now: `fixtures/cp-059-producer-billing-rows.json` is
 * GENERATED by PrepShip's real `toBillingDetailOrderRows`, committed, and asserted against here.
 * The portal no longer gets a vote on what the producer emits.
 */
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import {
  RETURN_LINE_TYPES,
  RETURN_POSTAGE_LINE_TYPES,
  RETURN_PROCESSING_LINE_TYPES,
} from '../src/services/billing-line-types';
import { readFileSync } from 'node:fs';

process.env.PREPSHIP_API_URL ??= 'http://canonical.test';
process.env.DATABASE_URL ??= 'postgres://u:p@127.0.0.1:5432/unused';
process.env.SUPABASE_JWT_SECRET ??= 'cp059-producer-guard';
process.env.NODE_ENV ??= 'test';

const { toCanonicalBillingEventRow, fetchCanonicalBillingDetails } =
  await import('../src/lib/client-portal/prepship-billing-details-proxy.js');
const { renderPortalInvoiceHtml } = await import('../src/lib/client-portal/invoice-html.js');
const { toPortalDetailRow } = await import(
  '../src/lib/client-portal/read-models/canonical-invoice-events.js'
);
const { buildInvoiceExcelSheet } = await import('../portal-client/src/lib/invoiceExcel.js');
const { invoiceRowKey } = await import('../portal-client/src/lib/invoiceRows.js');

let checks = 0;
const ok = (label: string) => { checks += 1; console.log(`ok   ${label}`); };

const FIXTURE = 'fixtures/cp-059-producer-billing-rows.json';
const fixture = JSON.parse(readFileSync(FIXTURE, 'utf8')) as {
  producerSha: string;
  contentHash: string;
  shapes: Array<{ name: string; rows: Array<Record<string, unknown>> }>;
};

// Provenance. A fixture with no recorded producer SHA is a fixture nobody can trace back to the
// code that produced it, which is how a stale contract survives unnoticed.
assert.match(fixture.producerSha, /^[0-9a-f]{40}$/, 'the fixture must record the producer SHA it came from');

/*
 * CONTENT-HASH ENFORCEMENT.
 *
 * The fixture recorded a contentHash from the day it was generated and nothing ever read it,
 * so the value was decoration: the shapes could be hand-edited — a total nudged, a presence
 * flag flipped — and every guard downstream would keep passing against the edited rows while
 * still claiming to test "the producer's own output".
 *
 * Recomputed and compared here. The scheme is the one the fixture was generated with:
 * sha256 over JSON.stringify(shapes).
 *
 * SCOPE, stated precisely so this is not read as more than it is. This proves the committed
 * rows are UNMODIFIED since generation — tamper evidence. It does NOT prove they still match
 * what prepship-v4 emits at producerSha; nothing in this repo re-runs the producer. Upstream
 * drift needs an exact-SHA producer/consumer parity lane against
 * src/services/billing-detail-row-sot.ts, the way the expedited-service contract is pinned.
 * Until that exists, producerSha is provenance METADATA and this hash is the only enforced
 * half.
 */
const recomputed = createHash('sha256').update(JSON.stringify(fixture.shapes)).digest('hex');
assert.equal(
  recomputed, fixture.contentHash,
  'the committed producer rows do not match their recorded contentHash — they were hand-edited, '
  + 'or regenerated without updating the hash. Either way these rows are no longer the producer\'s output.',
);
ok('the committed producer rows match their recorded contentHash (unmodified since generation)');

/*
 * RETURN VOCABULARY COVERAGE.
 *
 * The registry in services/billing-line-types.ts decides which line types count as return money
 * in BOTH summary authorities. Its first version was built by grepping this repo for
 * `line_type = '...'`, which finds only the spellings we currently WRITE — so it missed
 * `return`, `return_label` and `return_processing`, and the canonical return total it defined
 * computed $0.00 for the exact legacy shape it was introduced to fix.
 *
 * The producer's vocabulary is the authority, and the hash-enforced fixture is the copy of it we
 * hold. Read the vocabulary OUT of the fixture rather than restating it: a return type added
 * upstream then turns this guard red instead of silently zeroing a customer's return money.
 */
const producerReturnTypes = new Set<string>();
for (const shape of fixture.shapes) {
  for (const row of shape.rows as ReadonlyArray<{ lineTypes?: readonly string[] }>) {
    for (const lineType of row.lineTypes ?? []) {
      if (/return/.test(lineType)) producerReturnTypes.add(lineType);
    }
  }
}
assert.ok(producerReturnTypes.size > 0, 'the fixture must carry return line types to check against');
const registered = new Set<string>(RETURN_LINE_TYPES);
const unregistered = [...producerReturnTypes].filter((lineType) => !registered.has(lineType)).sort();
assert.deepEqual(
  unregistered, [],
  `RETURN_LINE_TYPES does not cover every return line type the producer emits: ${unregistered.join(', ')}. `
  + 'Any type missing here is return money that both summary authorities silently total as $0.00.',
);
ok(`the return registry covers all ${producerReturnTypes.size} producer return line types`);

/*
 * And the GROUPING matches the producer's own attribution, not just the membership. Getting
 * `return_label` into the registry but filing it under processing would keep returnTotal right
 * while making both named parts wrong.
 */
const POSTAGE = new Set<string>(RETURN_POSTAGE_LINE_TYPES);
const PROCESSING = new Set<string>(RETURN_PROCESSING_LINE_TYPES);
for (const shape of fixture.shapes) {
  for (const row of shape.rows as ReadonlyArray<{
    lineTypes?: readonly string[];
    returnTotal?: number; returnPostageTotal?: number; returnProcessingTotal?: number;
  }>) {
    const types = (row.lineTypes ?? []).filter((lineType) => /return/.test(lineType));
    if (types.length !== 1) continue;
    const [lineType] = types;
    const total = Number(row.returnTotal ?? 0);
    if (total === 0) continue;
    const postage = Number(row.returnPostageTotal ?? 0);
    const processing = Number(row.returnProcessingTotal ?? 0);
    if (POSTAGE.has(lineType)) {
      assert.equal(postage, total, `producer files '${lineType}' as POSTAGE (${shape.name})`);
    } else if (PROCESSING.has(lineType)) {
      assert.equal(processing, total, `producer files '${lineType}' as PROCESSING (${shape.name})`);
    } else {
      assert.equal(postage, 0, `'${lineType}' is BARE return money, not postage (${shape.name})`);
      assert.equal(processing, 0, `'${lineType}' is BARE return money, not processing (${shape.name})`);
    }
  }
}
ok('each return line type is grouped the way the producer attributes it');
assert.ok(fixture.shapes.length >= 11, `expected at least 11 producer shapes, got ${fixture.shapes.length}`);
console.log(`     producer SHA ${fixture.producerSha}, ${fixture.shapes.length} shapes`);
ok('the committed producer fixture records its provenance and covers every known shape');

// --- 1. EVERY producer row is accepted -------------------------------------------------------

const rejected: string[] = [];
const accepted: Array<Record<string, unknown>> = [];
for (const shape of fixture.shapes) {
  for (const row of shape.rows) {
    const mapped = toCanonicalBillingEventRow(row);
    if (mapped === null) rejected.push(shape.name);
    else accepted.push(mapped as unknown as Record<string, unknown>);
  }
}
assert.deepEqual(
  rejected, [],
  `the boundary rejected shapes PrepShip actually emits: ${[...new Set(rejected)].join(' | ')}\n`
  + 'A rejected row fails the WHOLE response, so each of these is a 502 for every period that '
  + 'contains one.',
);
ok(`all ${accepted.length} producer rows are accepted by the boundary`);

// The orderless storage rows specifically — the shape that caused the last failure.
const storageRows = accepted.filter((r) => r.orderId === null);
assert.ok(storageRows.length >= 3, `expected the orderless storage rows to survive, got ${storageRows.length}`);
ok(`${storageRows.length} ORDERLESS storage rows survive the boundary`);

// --- 2. identity is carried, and separates rows the old key collapsed ------------------------

for (const row of accepted) {
  assert.equal(typeof row.canonicalEventId, 'string', 'every accepted row carries the producer identity');
  assert.ok(String(row.canonicalEventId).length > 0, 'and it is never empty');
}
const ids = accepted.map((r) => String(r.canonicalEventId));
assert.equal(new Set(ids).size, ids.length, 'producer identities must stay distinct through the boundary');
ok('the producer identity is carried verbatim and stays distinct for every row');

// The two storage lines sharing a description are the case that used to collapse. Under the old
// key — orderId|returnId|rowType — both were `||Outbound`.
const twoStorage = fixture.shapes.find((s) => s.name.startsWith('TWO orderless storage'))!;
const twoMapped = twoStorage.rows.map((r) => toCanonicalBillingEventRow(r) as unknown as Record<string, unknown>);
assert.equal(twoMapped.length, 2, 'both storage rows must map');
const legacyKey = (r: Record<string, unknown>) => `${r.orderId ?? ''}|${r.returnId ?? ''}|${r.rowType ?? ''}`;
assert.equal(
  legacyKey(twoMapped[0]), legacyKey(twoMapped[1]),
  'setup check: the OLD key really did collapse these two rows — otherwise the next assertion proves nothing',
);
assert.notEqual(
  twoMapped[0].canonicalEventId, twoMapped[1].canonicalEventId,
  'two storage lines sharing a description must be distinguishable by the producer identity',
);
ok('two storage rows that the old key collapsed are separated by the producer identity');

// --- 2b. THE PROJECTION. The last step before the wire, and it drops what it does not name. ---
//
// The boundary validated the identity, the sort used it and the React key read it — and the
// projection that builds the served DTO simply did not list it, so the frontend received rows
// with no identity and fell back to the very key the identity exists to replace. No static guard
// could see it, because the projection was inline in a database-bound function. It is exported
// now, so this runs it.
const projected = accepted.map((row) => toPortalDetailRow(row as never));
for (const [index, row] of projected.entries()) {
  assert.equal(
    typeof (row as { canonicalEventId?: unknown }).canonicalEventId, 'string',
    `row ${index} lost its canonicalEventId in the projection — the DTO reaches the frontend `
    + 'with no identity, and two orderless storage rows become one',
  );
}
const projectedIds = projected.map((r) => String((r as { canonicalEventId?: unknown }).canonicalEventId));
assert.equal(new Set(projectedIds).size, projectedIds.length, 'identities must stay distinct through the projection');
ok('the served DTO carries a distinct identity for every row — the projection drops nothing');

// The projection is an allowlist, so it must also still drop what it should.
for (const forbidden of ['totalCost', 'lineTypes', 'margin', 'selectedRate', 'billingBadges']) {
  assert.ok(
    !(forbidden in (projected[0] as Record<string, unknown>)),
    `${forbidden} must not survive the projection onto a customer surface`,
  );
}
ok('the projection still drops internal fields — it is an allowlist, not a spread');

// The projection must also carry the MONEY CATEGORIES, or a real charge disappears from the
// itemized view while still sitting in the total — the PS-512 defect, one layer down.
for (const field of ['adjustmentTotal', 'replacePostageTotal', 'replacePickPackTotal']) {
  assert.ok(
    field in (projected[0] as Record<string, unknown>),
    `${field} must survive the projection — a category dropped here cannot reconcile to the total`,
  );
}
const replacementProjected = projected.filter(
  (r) => Number((r as Record<string, unknown>).replacePostageTotal ?? 0) > 0,
);
assert.ok(
  replacementProjected.length > 0,
  'the producer fixture must contain real replacement money that survives the projection',
);
ok('the projection carries adjustment and replacement money, with real non-zero amounts present');

// The React key is the producer identity, executed rather than eyeballed in a browser.
const storageProjected = projected.filter((r) => (r as Record<string, unknown>).orderId === null);
assert.ok(storageProjected.length >= 2, 'need at least two orderless rows to prove the key separates them');
const keys = storageProjected.map((r) => invoiceRowKey(r as never));
assert.equal(new Set(keys).size, keys.length, 'two orderless storage rows must get DIFFERENT React keys');
for (const key of keys) {
  assert.match(String(key), /^[0-9a-f]{32}$/, 'the React key is the producer identity, not a locally assembled string');
}
ok('the React key separates two orderless storage rows and is the producer identity verbatim');

// --- 3. no producer row renders fabricated money ---------------------------------------------

const html = renderPortalInvoiceHtml({
  clientName: 'Acme Fulfilment', dateFrom: '2026-08-01', dateTo: '2026-08-31',
  // The PROJECTED rows, not the raw boundary rows. The projection is what the route serves,
  // and it maps grandTotal -> rowTotal; rendering the boundary rows printed a $0.00 total on
  // every line, which went unnoticed until the reconciliation check below started reading it.
  details: projected as never, truncated: false,
  invoiceTotals: {
    orderCount: accepted.length, qty: 0, pickPackTotal: 0, additionalTotal: 0, packageTotal: 0,
    shippingTotal: 0, storageTotal: 0, grandTotal: 0,
  },
});
const bodyRows = (html.match(/<tbody>[\s\S]*?<\/tbody>/) ?? [''])[0]
  .split('</tr>').filter((c) => c.includes('<td'));
assert.equal(bodyRows.length, accepted.length, `every accepted row must render (${bodyRows.length} vs ${accepted.length})`);

// A row whose return fee is ABSENT must blank both return cells, whatever amount it carries.
const HTML_PROCESSING = 13;
const HTML_POSTAGE = 14;
for (const [index, row] of accepted.entries()) {
  const cells = [...bodyRows[index].matchAll(/<td[^>]*>([\s\S]*?)<\/td>/g)].map((m) => m[1].trim());
  assert.equal(cells.length, 19, `row ${index} rendered ${cells.length} cells`);
  if (row.hasReturnPostageLine === false) {
    assert.equal(cells[HTML_POSTAGE], '&mdash;',
      `an absent postage line must blank, not print the ${row.returnPostageTotal} it carries`);
  }
  if (row.hasReturnProcessingLine === false) {
    assert.equal(cells[HTML_PROCESSING], '&mdash;',
      `an absent processing line must blank, not print the ${row.returnProcessingTotal} it carries`);
  }
}
ok('no producer row prints a fabricated $0.00 in the printable invoice');

/*
 * FOOTER RECONCILIATION.
 *
 * Everything above reads the printed ROWS. The footer was never rendered with real totals —
 * the call above passes zeros — so the summary line escaped every check, and review found it
 * computing Return Total as `returnProcessingTotal + returnPostageTotal`.
 *
 * That addition is observably wrong for the producer's legacy bare-return shape, which funds
 * returnTotal while setting neither presence flag. Here the totals are deliberately
 * INCONSISTENT with that addition — returnTotal 15.50 against parts summing to 10.73 — so a
 * footer that re-derives prints 10.73 and a footer that renders the owned value prints 15.50.
 * Only one of those can pass.
 */
const footerHtml = renderPortalInvoiceHtml({
  clientName: 'Acme Fulfilment', dateFrom: '2026-08-01', dateTo: '2026-08-31',
  details: projected as never, truncated: false,
  invoiceTotals: {
    orderCount: accepted.length, qty: 0, pickPackTotal: 0, additionalTotal: 0, packageTotal: 0,
    shippingTotal: 0, storageTotal: 0,
    returnProcessingTotal: 3.0,
    returnPostageTotal: 7.73,
    // NOT 10.73. A bare return line funds this without touching either part.
    returnTotal: 15.5,
    adjustmentTotal: 0, replacePostageTotal: 0, replacePickPackTotal: 0,
    grandTotal: 15.5,
  } as never,
});
const footer = (footerHtml.match(/<tfoot>[\s\S]*?<\/tfoot>/) ?? footerHtml.match(/<tr class="totals"[\s\S]*?<\/tr>/) ?? [''])[0]
  || footerHtml.slice(footerHtml.lastIndexOf('</tbody>'));
assert.ok(
  footer.includes('$15.50'),
  'the footer must render the summary-owned returnTotal verbatim',
);
assert.ok(
  !footer.includes('$10.73'),
  'the footer must NOT re-derive Return Total by adding returnProcessing + returnPostage — '
  + 'that addition prints $0.00 for a legacy bare return line',
);
ok('the printable footer renders the owned Return Total, never the sum of its parts');

/*
 * VISIBLE RECONCILIATION — the check that would have caught the invisibility defect.
 *
 * Every earlier proof asked whether a field SURVIVED transport: `field in projectedRow`. That
 * stayed true while replacement and adjustment money reached the DTO and were rendered nowhere,
 * so a row printed components adding to $8.60 beneath a Fulfillment Fee of $20.35 — $11.75
 * hidden behind the total, on a customer's invoice.
 *
 * This reads the money out of the RENDERED CELLS and requires it to add up to the rendered
 * total. A category that is carried but not displayed fails here, which "is the property
 * present?" never could.
 *
 * The producer stays the money authority: the total is not recomputed and replaced, it is
 * compared. If they disagree, this fails rather than picking a winner.
 */
const cellMoney = (cell: string): number => {
  const text = cell.replace(/&mdash;|&nbsp;/g, '').replace(/[$,]/g, '').trim();
  if (text === '') return 0;
  const parsed = Number(text);
  assert.ok(Number.isFinite(parsed), `rendered cell is not money: ${JSON.stringify(cell)}`);
  return parsed;
};

// 6 Pick&Pack · 7 Addl · 8 Box Charge · 10 Shipping · 11 Storage · 12 Adjustment
// 13 Return Processing · 14 Return Postage · 15 Replacement Postage · 16 Replacement Pick&Pack
// Return Processing (13) and Return Postage (14) are breakouts WITHIN Return Total (15), so
// only the total participates — counting all three would double-count return money.
const HTML_COMPONENTS = [6, 7, 8, 10, 11, 12, 15, 16, 17];
const HTML_TOTAL = 18;

let reconciledRows = 0;
let rowsCarryingReplacement = 0;
for (const [index, chunk] of bodyRows.entries()) {
  const cells = [...chunk.matchAll(/<td[^>]*>([\s\S]*?)<\/td>/g)].map((m) => (m[1] ?? '').trim());
  const visible = HTML_COMPONENTS.reduce((sum, col) => sum + cellMoney(cells[col] ?? ''), 0);
  const printedTotal = cellMoney(cells[HTML_TOTAL] ?? '');
  assert.equal(
    Math.round(visible * 100) / 100, Math.round(printedTotal * 100) / 100,
    `row ${index}: the VISIBLE components (${visible}) do not add up to the printed total `
    + `(${printedTotal}). A category is carried but not displayed.`,
  );
  reconciledRows += 1;
  if (cellMoney(cells[16] ?? '') > 0 || cellMoney(cells[17] ?? '') > 0) rowsCarryingReplacement += 1;
}
// Setup check: if no row carried replacement money, the reconciliation above would hold for a
// trivial reason and prove nothing about the categories this exists to surface.
assert.ok(
  rowsCarryingReplacement > 0,
  'no rendered row carried replacement money — this check would pass vacuously',
);
ok(`all ${reconciledRows} printed rows reconcile from VISIBLE cells, ${rowsCarryingReplacement} carrying replacement money`);

const { sheet } = buildInvoiceExcelSheet(projected as never);
assert.equal(sheet.length, accepted.length + 2, 'header + every row + totals');
ok('every producer row survives into the spreadsheet export');

// The same property in the spreadsheet, where a hidden category is worse: the numbers get
// summed, filtered and reconciled by whoever opens it.
const xlsxHeaders = (sheet[0] as Array<{ value: string }>).map((c) => c?.value);
for (const label of ['Replacement Postage', 'Replacement Pick & Pack', 'Adjustment']) {
  assert.ok(xlsxHeaders.includes(label), `the export must have a ${label} column`);
}
const colOf = (label: string) => xlsxHeaders.indexOf(label);
const XLSX_COMPONENTS = ['Pick & Pack', 'Addl Units', 'Box Charge', 'Shipping', 'Storage',
  'Adjustment', 'Return Total', 'Replacement Postage',
  'Replacement Pick & Pack'].map(colOf);
const XLSX_TOTAL = colOf('Fulfillment Fee');
assert.ok(XLSX_TOTAL > 0 && XLSX_COMPONENTS.every((c) => c > 0), 'every expected column is present');

const xlsxCellValue = (cell: unknown): number => {
  const value = (cell as { value?: unknown })?.value;
  return typeof value === 'number' ? value : 0;
};
let xlsxReconciled = 0;
for (const row of sheet.slice(1, -1)) {
  const cells = row as unknown[];
  const visible = XLSX_COMPONENTS.reduce((sum, col) => sum + xlsxCellValue(cells[col]), 0);
  const total = xlsxCellValue(cells[XLSX_TOTAL]);
  assert.equal(
    Math.round(visible * 100) / 100, Math.round(total * 100) / 100,
    `a spreadsheet row's visible components (${visible}) do not add up to its total (${total})`,
  );
  xlsxReconciled += 1;
}
ok(`all ${xlsxReconciled} spreadsheet rows reconcile from visible numeric cells`);

// --- 4. the whole fixture passes through the response boundary as one payload -----------------

const originalFetch = globalThis.fetch;
globalThis.fetch = (async () => new Response(
  JSON.stringify({ data: fixture.shapes.flatMap((s) => s.rows) }),
  { status: 200, headers: { 'content-type': 'application/json' } },
)) as typeof fetch;
const whole = await fetchCanonicalBillingDetails('Bearer t', { dateFrom: '2026-08-01', dateTo: '2026-09-01' });
globalThis.fetch = originalFetch;
assert.ok(whole.ok, `the full producer payload must not fail the response boundary: ${whole.ok ? '' : whole.code}`);
assert.equal(whole.rows.length, accepted.length, 'every producer row survives the response boundary');
ok('the entire producer payload passes the response boundary in one piece');

const EXPECTED_CHECKS = 18;
assert.equal(checks, EXPECTED_CHECKS, `expected ${EXPECTED_CHECKS} checks; ${checks} ran`);
console.log('');
console.log(`PASS CP-059 producer contract guard - ${checks}/${EXPECTED_CHECKS} checks`);
