/* CP-068 — the portal's invoice Export is PrepShip's workbook, passed through.
 *
 * The proxy guard (scripts/client-portal-invoice-export-proxy-guard.ts) proves the boundary in
 * isolation. This proves what only the real router and a real database can: that scope,
 * financials, the bearer and client VISIBILITY are all decided before PrepShip is called, that
 * the caller's bearer and plain DAYS are what reach the wire, and that the bytes the customer
 * downloads are the producer's own — byte-identical to a workbook PrepShip's real
 * renderInvoiceXlsx produced, a valid ZIP that jszip opens, whose first row is PrepShip's
 * 19-column header.
 *
 * The upstream is stubbed with a committed fixture generated by PrepShip's real renderer
 * (fixtures/cp-068-prepship-invoice-workbook.*, provenance in the sidecar). Pointing this at a
 * live instance would make the bytes non-deterministic while proving nothing extra about the
 * portal. What is real is the Postgres the client-visibility check runs against.
 *
 * No production data. No billing regeneration. No network beyond the stub.
 */
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { sql as rawSql } from 'drizzle-orm';
import { Hono } from 'hono';
import JSZip from 'jszip';
import { setupTestEnv } from './guard';

setupTestEnv();
process.env.PREPSHIP_API_URL ??= 'http://canonical.test';

const { db, sql: pgClient } = await import('../../src/db/client');
const invoiceExportApp = (await import('../../src/routes/client-portal/invoice-export')).default;

let checks = 0;
const ok = (label: string) => { checks += 1; console.log(`ok   ${label}`); };

/**
 * PrepShip's column contract, pinned HERE as a literal — not read from the sidecar — so the
 * fixture cannot be regenerated against a drifted producer without this suite noticing. It
 * mirrors prepship-v4 src/routes/billing-invoice-columns.ts (append-only: a 20th column is
 * allowed after these; a change inside them is not).
 */
const PREPSHIP_INVOICE_HEADERS = [
  'Billing / Activity Date (Los Angeles)', 'Order #', 'SKUs', 'Box Size', 'Box Cost', 'Qty',
  'Pick & Pack Fee', 'Additional Units', 'Shipping', 'Storage', 'Total', 'Shipment #',
  'Destination', 'Return Postage', 'Return Processing', 'Replace Postage', 'Replace Pick&Pack',
  'Carrier', 'Item Name',
] as const;

const XLSX_TYPE = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
const FIXTURE_BYTES = new Uint8Array(readFileSync('fixtures/cp-068-prepship-invoice-workbook.xlsx'));
const FIXTURE = JSON.parse(readFileSync('fixtures/cp-068-prepship-invoice-workbook.json', 'utf8')) as {
  producerSha: string; sha256: string; sheet: string; headers: string[]; dataRows: number;
};
const sha256 = (bytes: Uint8Array) => createHash('sha256').update(bytes).digest('hex');

const decodeXml = (text: string) => text
  .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&amp;/g, '&');

/** Row 1 of the first worksheet, cell by cell, resolving shared and inline strings. */
async function headerRowOf(bytes: Uint8Array): Promise<{
  sheetNames: string[]; headers: string[]; lastRow: number; totalsFormulas: string[];
}> {
  const zip = await JSZip.loadAsync(bytes);
  const workbook = await zip.file('xl/workbook.xml')!.async('string');
  const sheetNames = [...workbook.matchAll(/<sheet\b[^>]*\bname="([^"]*)"/g)].map((m) => decodeXml(m[1]!));
  const sheet = await zip.file('xl/worksheets/sheet1.xml')!.async('string');
  const sharedXml = await zip.file('xl/sharedStrings.xml')?.async('string');
  const shared = sharedXml
    ? [...sharedXml.matchAll(/<si>([\s\S]*?)<\/si>/g)]
      .map((m) => [...m[1]!.matchAll(/<t[^>]*>([^<]*)<\/t>/g)].map((t) => decodeXml(t[1]!)).join(''))
    : [];
  const rowOne = /<row\b[^>]*\br="1"[^>]*>([\s\S]*?)<\/row>/.exec(sheet)?.[1] ?? '';
  const headers = [...rowOne.matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)].map(([, attrs, inner]) => {
    const type = /\bt="(\w+)"/.exec(attrs!)?.[1];
    const value = /<v>([^<]*)<\/v>/.exec(inner!)?.[1] ?? '';
    if (type === 's') return shared[Number(value)] ?? '';
    if (type === 'inlineStr') return decodeXml(/<t[^>]*>([^<]*)<\/t>/.exec(inner!)?.[1] ?? '');
    return decodeXml(value);
  });
  const lastRow = Math.max(0, ...[...sheet.matchAll(/<row\b[^>]*\br="(\d+)"/g)].map((m) => Number(m[1])));
  // The totals row: PrepShip writes its money totals as SUM() FORMULAS over the data rows, never
  // as numbers it added up itself. Formulas live in <f> elements on the last row.
  const lastRowXml = new RegExp(`<row\\b[^>]*\\br="${lastRow}"[^>]*>([\\s\\S]*?)</row>`).exec(sheet)?.[1] ?? '';
  const totalsFormulas = [...lastRowXml.matchAll(/<f>([^<]*)<\/f>/g)].map((m) => decodeXml(m[1]!));
  return { sheetNames, headers, lastRow, totalsFormulas };
}

async function main(): Promise<void> {
  // The fixture itself must be what the sidecar says it is, or every assertion below is about
  // bytes nobody can trace back to the producer.
  if (sha256(FIXTURE_BYTES) !== FIXTURE.sha256) throw new Error('the committed workbook does not match its recorded sha256');
  if (!/^[0-9a-f]{40}$/.test(FIXTURE.producerSha)) throw new Error('the fixture must record the producer SHA it came from');
  ok(`fixture provenance: ${FIXTURE_BYTES.byteLength} bytes from producer ${FIXTURE.producerSha.slice(0, 8)}, sha256 intact`);

  await db.execute(rawSql`delete from clients where id in (7907, 7908)`);
  await db.execute(rawSql`insert into clients (id, name) values (7907, 'CP068 Route Client'), (7908, 'CP068 Other Client')`);

  type UpstreamCapture = { calls: number; url: string; authorization: string | null };
  const upstream: UpstreamCapture = { calls: 0, url: '', authorization: null };
  // Read through a call so TypeScript cannot narrow a captured value to its last literal and
  // then reject the next comparison as "no overlap".
  const wire = (): UpstreamCapture => ({ ...upstream });
  const stubUpstream = (body: string | Uint8Array | null, init: { status?: number; headers?: Record<string, string> } = {}) => {
    upstream.calls = 0; upstream.url = ''; upstream.authorization = null;
    globalThis.fetch = (async (input: unknown, requestInit?: RequestInit) => {
      upstream.calls += 1;
      upstream.url = typeof input === 'string' ? input : String((input as { url?: string })?.url ?? input);
      upstream.authorization = new Headers(requestInit?.headers ?? {}).get('authorization');
      return new Response(body, { status: init.status ?? 200, headers: init.headers ?? {} });
    }) as typeof fetch;
  };
  const stubWorkbook = () => stubUpstream(FIXTURE_BYTES, {
    headers: {
      'content-type': XLSX_TYPE,
      'content-disposition': 'attachment; filename="invoice-CP068-Fixture-Client-2026-08-01-2026-08-31.xlsx"',
    },
  });

  const mount = (vars: Record<string, unknown>) => {
    const harness = new Hono();
    harness.use('*', async (c, next) => {
      for (const [key, value] of Object.entries(vars)) c.set(key as never, value as never);
      await next();
    });
    harness.route('/', invoiceExportApp);
    return harness;
  };
  const RANGE = 'dateFrom=2026-08-01&dateTo=2026-08-31';
  const financials = {
    userId: 'cp068-route', email: 'route@cp068.test', role: 'client',
    permissions: ['financials:read'], clientIds: [7907], storeIds: [],
  };
  const BEARER = 'Bearer cp068-caller-token';
  const get = (app: Hono, path: string, bearer: string | null = BEARER) =>
    app.request(path, { headers: bearer ? { authorization: bearer } : {} });

  // --- 1. the happy path: PrepShip's bytes, unmodified, as a valid 19-column workbook ----------
  stubWorkbook();
  const happy = await get(mount(financials), `/invoice.xlsx?clientId=7907&${RANGE}`);
  if (happy.status !== 200) throw new Error(`expected 200, got ${happy.status}: ${await happy.text()}`);
  if (happy.headers.get('content-type') !== XLSX_TYPE) throw new Error(`content-type: ${happy.headers.get('content-type')}`);
  if (happy.headers.get('content-disposition') !== 'attachment; filename="invoice-CP068-Fixture-Client-2026-08-01-2026-08-31.xlsx"') {
    throw new Error(`PrepShip's filename must pass through, got ${happy.headers.get('content-disposition')}`);
  }
  if (happy.headers.get('x-content-type-options') !== 'nosniff') throw new Error('nosniff must be set');
  if (happy.headers.get('cache-control') !== 'no-store') throw new Error('a customer invoice must not be cached');
  const served = new Uint8Array(await happy.arrayBuffer());
  if (sha256(served) !== FIXTURE.sha256) throw new Error('the served bytes are not the producer\'s bytes');
  if (served.byteLength !== Number(happy.headers.get('content-length'))) throw new Error('content-length must match the bytes');
  ok('GET /invoice.xlsx serves PrepShip\'s bytes byte-identical, with its filename, nosniff and no-store');

  if (wire().calls !== 1) throw new Error(`expected exactly one upstream call, got ${wire().calls}`);
  if (wire().url !== 'http://canonical.test/billing/invoice.xlsx?clientId=7907&dateFrom=2026-08-01&dateTo=2026-08-31') {
    throw new Error(`the wire must carry the client and plain DAYS, got ${wire().url}`);
  }
  if (wire().authorization !== BEARER) throw new Error(`the caller bearer must be forwarded verbatim, got ${wire().authorization}`);
  ok('one upstream call carrying the caller bearer and YYYY-MM-DD days (dateTo=2026-08-31, not an exclusive 09-01)');

  const parsed = await headerRowOf(served);
  if (!parsed.sheetNames.includes(FIXTURE.sheet)) throw new Error(`expected a '${FIXTURE.sheet}' sheet, got ${parsed.sheetNames.join('|')}`);
  if (parsed.headers.length < PREPSHIP_INVOICE_HEADERS.length) {
    throw new Error(`expected at least ${PREPSHIP_INVOICE_HEADERS.length} header cells, got ${parsed.headers.length}: ${parsed.headers.join('|')}`);
  }
  PREPSHIP_INVOICE_HEADERS.forEach((expected, index) => {
    if (parsed.headers[index] !== expected) {
      throw new Error(`header ${index + 1} must be '${expected}', got '${parsed.headers[index]}' — PrepShip's column contract drifted`);
    }
  });
  if (FIXTURE.headers.join('|') !== parsed.headers.join('|')) throw new Error('the sidecar header list must match the workbook');
  // header + data rows + the SUM() totals row
  if (parsed.lastRow !== FIXTURE.dataRows + 2) throw new Error(`expected ${FIXTURE.dataRows + 2} rows, got ${parsed.lastRow}`);
  ok(`the served file is a valid workbook: sheet '${FIXTURE.sheet}', row 1 is PrepShip's ${PREPSHIP_INVOICE_HEADERS.length}-column header, ${FIXTURE.dataRows} data rows + totals`);

  // The totals row is PrepShip's arithmetic, expressed as formulas over exactly the data rows —
  // the portal added nothing up. Seven money/qty columns are summed (Box Cost, Qty, Pick & Pack
  // Fee, Additional Units, Shipping, Storage, Total — billing.ts sumOf()); each spans row 2 to
  // the last data row.
  const firstData = 2;
  const lastData = parsed.lastRow - 1;
  // Two captures compared in code rather than a backreference: `\1` followed by a digit reads
  // as `\14`, a different group entirely.
  const sumShape = new RegExp(`^SUM\\(([A-Z]+)${firstData}:([A-Z]+)${lastData}\\)$`);
  const badFormula = parsed.totalsFormulas.find((formula) => {
    const match = sumShape.exec(formula);
    return !match || match[1] !== match[2];
  });
  if (parsed.totalsFormulas.length !== 7) {
    throw new Error(`expected 7 SUM() formulas on the totals row, got ${parsed.totalsFormulas.length}: ${parsed.totalsFormulas.join(' | ')}`);
  }
  if (badFormula) throw new Error(`a totals-row formula does not span the data rows ${firstData}..${lastData}: ${badFormula}`);
  ok(`the totals row carries PrepShip's 7 SUM() formulas over rows ${firstData}..${lastData} — no portal arithmetic`);

  // --- 2. denials never reach PrepShip ---------------------------------------------------------
  stubWorkbook();
  const noBearer = await get(mount(financials), `/invoice.xlsx?clientId=7907&${RANGE}`, null);
  if (noBearer.status !== 401) throw new Error(`missing bearer must be 401, got ${noBearer.status}`);
  if (wire().calls !== 0) throw new Error('an unauthenticated request must never reach upstream');
  ok('no bearer → 401, no upstream call');

  stubWorkbook();
  const noScope = await get(mount({ userId: 'nobody', permissions: [], clientIds: [], storeIds: [] }), `/invoice.xlsx?clientId=7907&${RANGE}`);
  if (noScope.status !== 403) throw new Error(`an unscoped caller must be 403, got ${noScope.status}`);
  if (wire().calls !== 0) throw new Error('an unscoped request must never reach upstream');
  ok('no client/store scope → 403, no upstream call');

  stubWorkbook();
  const noFinancials = await get(mount({ ...financials, permissions: [] }), `/invoice.xlsx?clientId=7907&${RANGE}`);
  if (noFinancials.status !== 403) throw new Error(`no financials:read must be 403, got ${noFinancials.status}`);
  if (wire().calls !== 0) throw new Error('a caller without financials:read must never reach upstream');
  ok('scoped but without financials:read → 403, no upstream call');

  stubWorkbook();
  const otherClient = await get(mount(financials), `/invoice.xlsx?clientId=7908&${RANGE}`);
  if (otherClient.status !== 404) throw new Error(`a client outside the caller's scope must be 404, got ${otherClient.status}`);
  if (wire().calls !== 0) throw new Error('an out-of-scope client must never reach upstream');
  const unknownClient = await get(mount(financials), `/invoice.xlsx?clientId=7999&${RANGE}`);
  if (unknownClient.status !== 404 || wire().calls !== 0) throw new Error('an unknown client must be 404 with no upstream call');
  ok('a client outside the caller\'s scope (or unknown) → 404, no upstream call');

  stubWorkbook();
  const noClient = await get(mount(financials), `/invoice.xlsx?${RANGE}`);
  if (noClient.status !== 400) throw new Error(`a multi-client ask must be 400 until DJ decides, got ${noClient.status}`);
  const badRange = await get(mount(financials), '/invoice.xlsx?clientId=7907&dateFrom=nope&dateTo=2026-08-31');
  if (badRange.status !== 400) throw new Error(`a malformed range must be 400, got ${badRange.status}`);
  if (wire().calls !== 0) throw new Error('a rejected ask must never reach upstream');
  ok('no clientId or a malformed range → 400, no upstream call');

  // --- 3. fail closed: nothing that is not the producer's file is ever served ------------------
  stubUpstream('<html>Sign in</html>', { headers: { 'content-type': 'text/html; charset=utf-8' } });
  const htmlPage = await get(mount(financials), `/invoice.xlsx?clientId=7907&${RANGE}`);
  if (htmlPage.status !== 502) throw new Error(`a 200 HTML page must fail closed, got ${htmlPage.status}`);
  if ((htmlPage.headers.get('content-type') ?? '').startsWith(XLSX_TYPE)) throw new Error('an error must never be labelled a workbook');
  ok('an upstream 200 that is not a workbook → 502, never served as one');

  stubUpstream('boom', { status: 500 });
  const upstreamDown = await get(mount(financials), `/invoice.xlsx?clientId=7907&${RANGE}`);
  if (upstreamDown.status !== 502) throw new Error(`an upstream 500 must be 502, got ${upstreamDown.status}`);
  stubUpstream('Forbidden', { status: 403 });
  const upstreamForbidden = await get(mount(financials), `/invoice.xlsx?clientId=7907&${RANGE}`);
  if (upstreamForbidden.status !== 403) throw new Error(`an upstream 403 must stay 403, got ${upstreamForbidden.status}`);
  if ((await upstreamForbidden.text()) !== 'Not found') throw new Error('an upstream denial must carry no detail');
  ok('upstream 500 → 502; upstream 403 → 403 with a generic detail');

  stubUpstream(FIXTURE_BYTES, { headers: { 'content-type': XLSX_TYPE, 'content-disposition': 'attachment; filename="../etc/passwd.xlsx"' } });
  const unsafeName = await get(mount(financials), `/invoice.xlsx?clientId=7907&${RANGE}`);
  if (unsafeName.status !== 200) throw new Error(`expected 200, got ${unsafeName.status}`);
  if (unsafeName.headers.get('content-disposition') !== 'attachment; filename="invoice-7907-2026-08-01-2026-08-31.xlsx"') {
    throw new Error(`an unsafe upstream filename must be replaced, got ${unsafeName.headers.get('content-disposition')}`);
  }
  ok('an unsafe upstream filename is replaced by a portal-built safe one; the bytes still pass through');

  // --- 4. the CSV rides the same proxy ---------------------------------------------------------
  const csvBody = `${PREPSHIP_INVOICE_HEADERS.join(',')}\n2026-08-05,9001,SKU-A,Small,0.00,1,2.50,0.00,6.10,0.00,8.60,#5001,Domestic,,,,,USPS,Widget A\n`;
  stubUpstream(csvBody, { headers: { 'content-type': 'text/csv; charset=utf-8', 'content-disposition': 'attachment; filename="invoice-CP068-Fixture-Client-2026-08-01-2026-08-31.csv"' } });
  const csv = await get(mount(financials), `/invoice.csv?clientId=7907&${RANGE}`);
  if (csv.status !== 200) throw new Error(`expected 200 for the CSV, got ${csv.status}`);
  if ((await csv.text()) !== csvBody) throw new Error('the CSV bytes must pass through unmodified');
  if (csv.headers.get('content-type') !== 'text/csv') throw new Error(`csv content-type: ${csv.headers.get('content-type')}`);
  if (wire().url !== 'http://canonical.test/billing/invoice.csv?clientId=7907&dateFrom=2026-08-01&dateTo=2026-08-31') {
    throw new Error(`the CSV must be asked for with plain days, got ${wire().url}`);
  }
  stubUpstream(csvBody, { headers: { 'content-type': XLSX_TYPE } });
  const csvWrongType = await get(mount(financials), `/invoice.csv?clientId=7907&${RANGE}`);
  if (csvWrongType.status !== 502) throw new Error(`a CSV labelled as a workbook must fail closed, got ${csvWrongType.status}`);
  ok('GET /invoice.csv passes PrepShip\'s CSV through under the same rules');

  await db.execute(rawSql`delete from clients where id in (7907, 7908)`);
}

try {
  await main();
  const EXPECTED_CHECKS = 14;
  if (checks !== EXPECTED_CHECKS) throw new Error(`expected ${EXPECTED_CHECKS} checks; ${checks} ran`);
  console.log(`\nPASS CP-068 invoice-export pass-through integration - ${checks}/${EXPECTED_CHECKS} checks`);
} finally {
  await pgClient.end({ timeout: 5 });
}
